- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name:
      - python3
      - python3-pip
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - curl
    state: present